config/routes.rb
Demo::Application.routes.draw do

  match '/home', :to => 'pages#home'
  match '/contact',   :to => 'pages#contact'

  match '/signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

  resources :microposts

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => 'pages#home'

end

app/views/layouts/_head.erb
<title><%= title %></title>
<%= stylesheet_link_tag    "bootstrap", :media => "all" %>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= javascript_include_tag :defaults %>

app/views/layouts/_top_nav.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to logo, root_path %>

      <ul class="nav">
        <li><%= link_to 'Home', home_path%></li>

        <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <% end %>

        <li><%= link_to 'Contact', contact_path %></li>

        <% if signed_in? %>
            <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to 'Signup', signup_path %></li>
        <% end %>



      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= render 'layouts/head' %>
</head>
<body>

    <%= render 'layouts/top_nav' %>

    <div class="container" style="margin-top: 50px;">

        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>

        <%= yield %>
    </div>

<div class="footer" style="margin-top: 50px;">
  <%= debug(params) if Rails.env.development? %>
</div>



</body>
</html>